[package]
name = "lisp_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib", "lib"]

[target.'cfg(target_arch = "x86_64")'.dependencies]
rustyline = "10.0.0"
pico-args = "0.5.0"

[dependencies]
wasm-bindgen = "0.2.86"
